language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"

# command to install dependencies
install:
  - pip install .
  - pip install -r testrequirements.txt

# command to run tests
script: python dAES-tests.py
